# Generated by Django 6.0.4 on 2026-05-01 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens_servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.TextField()),
                ('tabela_afetada', models.CharField(max_length=100)),
                ('id_registro_afetado', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('os_aberta', 'OS Aberta'), ('os_atualizada', 'OS Atualizada'), ('os_concluida', 'OS Concluída'), ('plano_vencendo', 'Plano Vencendo')], max_length=30)),
                ('canal', models.CharField(choices=[('push', 'Push Notification'), ('email', 'E-mail')], default='push', max_length=10)),
                ('timestamp_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('id_os', models.ForeignKey(blank=True, db_column='id_os', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='ordens_servico.ordemservico')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacoes',
                'ordering': ['-timestamp_envio'],
            },
        ),
    ]
