# Generated by Django 6.0.4 on 2026-05-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(blank=True, default=''),
        ),
    ]
