# Generated by Django 6.0.4 on 2026-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(default='', max_length=120),
        ),
    ]
