# Generated by Django 6.0.4 on 2026-05-01 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('tipo_manutencao', models.CharField(choices=[('preditiva', 'Preditiva'), ('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=20)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('relatorio_intervencao', models.TextField(blank=True, null=True)),
                ('timestamp_retorno_operacao', models.DateTimeField(blank=True, null=True)),
                ('id_equipamento', models.ForeignKey(db_column='id_equipamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='equipamentos.equipamento')),
                ('solicitante', models.ForeignKey(db_column='id_solicitante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, db_column='id_tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atribuidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordens_servico',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
