# Generated by Django 6.0.4 on 2026-05-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0001_initial'),
        ('usuarios', '0003_alter_usuariosetor_perfil_no_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico',
            field=models.ForeignKey(blank=True, db_column='id_usuario_setor', limit_choices_to={'perfil_no_setor': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atribuidas', to='usuarios.usuariosetor'),
        ),
    ]
