# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0003_equipamento_manutencao_datas"),
        ("ordens_servico", "0002_alter_ordemservico_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="proxima_manutencao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
