# Generated by Django 6.0.4 on 2026-10-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_planomanutencao_ultima_manutencao'),
        ('ordens_servico', '0003_ordemservico_proxima_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='plano_origem',
            field=models.ForeignKey(blank=True, db_column='id_plano_origem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_geradas', to='manutencao.planomanutencao'),
        ),
    ]
