# Generated by Django 6.0.4 on 2026-10-04 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0004_ordemservico_plano_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriagemIA',
            fields=[
                ('id_triagem', models.AutoField(primary_key=True, serialize=False)),
                ('texto_original', models.TextField()),
                ('tipo_problema', models.CharField(choices=[('mecanico', 'Mecânico'), ('eletrico', 'Elétrico'), ('hidraulico', 'Hidráulico'), ('software', 'Software'), ('outro', 'Outro')], max_length=20)),
                ('justificativa_prioridade', models.TextField()),
                ('confianca', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('modelo_usado', models.CharField(max_length=100)),
                ('prioridade_sugerida', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('id_os', models.OneToOneField(db_column='id_os', on_delete=django.db.models.deletion.CASCADE, related_name='triagem_ia', to='ordens_servico.ordemservico')),
            ],
            options={
                'db_table': 'triagens_ia',
            },
        ),
    ]
