# Generated by Django 6.0.4 on 2026-05-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_setor'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoManutencao',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('preditiva', 'Preditiva')], max_length=20)),
                ('periodicidade_dias', models.PositiveIntegerField()),
                ('proxima_execucao', models.DateField()),
                ('id_equipamento', models.ForeignKey(db_column='id_equipamento', on_delete=django.db.models.deletion.CASCADE, related_name='planos_manutencao', to='equipamentos.equipamento')),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_manutencao', to='empresas.setor')),
            ],
            options={
                'db_table': 'planos_manutencao',
                'ordering': ['proxima_execucao'],
            },
        ),
    ]
