# Generated by Django 6.0.4 on 2026-05-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('manutencao', '0001_initial'),
        ('ordens_servico', '0002_alter_ordemservico_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('valor_limite', models.FloatField()),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10)),
                ('detectada_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('os_gerada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordens_servico.ordemservico')),
            ],
            options={
                'db_table': 'anomalia_iot',
            },
        ),
    ]
