# Generated by Django 6.0.4 on 2026-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_anomaliaiot'),
    ]

    operations = [
        migrations.AddField(
            model_name='planomanutencao',
            name='ultima_manutencao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
