# Generated by Django 6.0.4 on 2026-05-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_equipamento',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('data_entrada_operacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_manutencao', 'Em Manutenção')], default='ativo', max_length=20)),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='empresas.setor')),
                ('id_tipo', models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='equipamentos.tipoequipamento')),
            ],
            options={
                'db_table': 'equipamentos',
            },
        ),
    ]
