# Generated by Django 6.0.4 on 2026-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tem_iot',
            field=models.BooleanField(default=False),
        ),
    ]
