# Generated by Codex on 2026-05-25

from django.db import migrations, models


def preencher_ultima_manutencao(apps, schema_editor):
    equipamento_model = apps.get_model("equipamentos", "Equipamento")
    ordem_model = apps.get_model("ordens_servico", "OrdemServico")

    for equipamento in equipamento_model.objects.all():
        ultima_os = (
            ordem_model.objects.filter(
                id_equipamento=equipamento,
                status="concluida",
                data_fim__isnull=False,
            )
            .order_by("-data_fim")
            .first()
        )
        if ultima_os is not None:
            equipamento.ultima_manutencao = ultima_os.data_fim
            equipamento.save(update_fields=["ultima_manutencao"])


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0002_equipamento_tem_iot"),
        ("ordens_servico", "0002_alter_ordemservico_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="ultima_manutencao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="proxima_manutencao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(preencher_ultima_manutencao, migrations.RunPython.noop),
    ]
