# Generated by Django 6.0.4 on 2026-05-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_setor'),
        ('equipamentos', '0003_equipamento_manutencao_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_equipamento', to='empresas.empresa'),
        ),
    ]
