# Generated by Django 6.0.4 on 2026-05-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
