# Generated by Django 6.0.4 on 2026-05-01 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_setor'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_no_setor', models.CharField(choices=[('gestor', 'Gestor'), ('operador', 'Operador'), ('visualizador', 'Visualizador')], default='operador', max_length=20)),
                ('id_setor', models.ForeignKey(db_column='id_setor', on_delete=django.db.models.deletion.CASCADE, related_name='usuariosetor_set', to='empresas.setor')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuariosetor_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_setor',
                'unique_together': {('id_usuario', 'id_setor')},
            },
        ),
    ]
