# Generated by Django 6.0.4 on 2026-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariosetor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosetor',
            name='perfil_no_setor',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('operador', 'Operador'), ('visualizador', 'Visualizador'), ('tecnico', 'Técnico')], default='operador', max_length=20),
        ),
    ]
