# Generated by Django 6.0.4 on 2026-05-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_perfil'),
        ('usuarios', '0003_alter_usuariosetor_perfil_no_setor'),
    ]

    operations = [
    ]
