# Generated by Django 6.0.4 on 2026-06-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_20260520_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
